# Generated by Django 2.0.9 on 2018-10-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='seo_secondary_image_alt',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Secondary Image Alt (SEO)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='seo_main_image_alt',
            field=models.CharField(blank=True, max_length=68, null=True, verbose_name='Main Image Alt (SEO)'),
        ),
    ]
