# Generated by Django 2.0.9 on 2018-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181021_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='taglinktopmenu',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
