# Generated by Django 2.0.9 on 2018-10-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181015_1630'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
    ]
