# Generated by Django 2.0.9 on 2018-10-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0004_merge_20181018_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
