# Generated by Django 2.0.9 on 2018-10-21 12:12

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_taglinktopmenu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLinkLeftMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_handler',
            field=models.CharField(blank=True, max_length=255, verbose_name='twitter handler'),
        ),
        migrations.AddField(
            model_name='taglinkleftmenu',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_menu', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='taglinkleftmenu',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tag'),
        ),
    ]
