# Generated by Django 2.0.9 on 2018-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181024_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taglinkleftsubmenu',
            name='icon',
            field=models.CharField(help_text='You should use icon\'s names from Font Awesome. You can check the list here: <a href="https://fontawesome.com/icons?d=gallery" target="_blank">Icon Gallery</a>.', max_length=255, verbose_name='icon'),
        ),
    ]
