# Generated by Django 2.0.9 on 2018-10-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='enable_paywall',
            field=models.BooleanField(default=False, help_text='Enable the paywall, UI blocker for AVP pages if the user is not suscribed', verbose_name='enable paywall'),
        ),
    ]
