# Generated by Django 2.0.9 on 2018-10-29 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_globalsettings_enable_paywall'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='talent_of_the_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talented_at', to=settings.AUTH_USER_MODEL, verbose_name='talent of the week'),
        ),
    ]
