# Generated by Django 2.0.9 on 2018-10-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_podcastepisodepage_podcastpage_videopage'),
        ('home', '0011_homepage_talent_of_the_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article.ArticlePage', verbose_name='articles'),
        ),
    ]
