# Generated by Django 2.0.9 on 2018-11-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181031_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='live_radio_link',
            field=models.URLField(blank=True, verbose_name='live radio link'),
        ),
    ]
