# Generated by Django 2.0.9 on 2018-10-18 18:46

from django.conf import settings
from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='author_on', to=settings.AUTH_USER_MODEL, verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='contributors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='contributor_on', to=settings.AUTH_USER_MODEL, verbose_name='contributors'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='editors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='editor_on', to=settings.AUTH_USER_MODEL, verbose_name='editors'),
        ),
    ]
