# Generated by Django 2.0.9 on 2018-10-17 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20181017_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='author',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='author_on', to=settings.AUTH_USER_MODEL, verbose_name='authors'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributor_on', to=settings.AUTH_USER_MODEL, verbose_name='contributors'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editor_on', to=settings.AUTH_USER_MODEL, verbose_name='editors'),
        ),
    ]
