# Generated by Django 2.0.9 on 2018-10-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('article', '0004_auto_20181019_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_image_on', to='wagtailimages.Image', verbose_name='Featured Image'),
        ),
    ]
