# Generated by Django 2.0.9 on 2018-10-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepage_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisodePage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.ArticlePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='PodcastPage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.ArticlePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.ArticlePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('article.articlepage',),
        ),
    ]
