# Generated by Django 2.0.9 on 2018-10-31 11:56

from django.db import migrations


def delete_podcasts(apps, schema_editor):
    PodcastPage = apps.get_model('article', 'PodcastPage')
    PodcastEpisodePage = apps.get_model('article', 'PodcastEpisodePage')
    PodcastPage.objects.all().delete()
    PodcastEpisodePage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_podcastepisodepage_podcastpage_videopage'),
    ]

    operations = [
        migrations.RunPython(delete_podcasts, migrations.RunPython.noop),
    ]
