# Generated by Django 2.0.9 on 2018-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20181031_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisodepage',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Episode Number'),
        ),
    ]
