# Generated by Django 2.0.9 on 2018-10-16 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Profile = apps.get_model('user', 'Profile')
    for user in User.objects.all():
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
                'ordering': ('-created',),
            },
        ),
        migrations.RunPython(create_profiles, migrations.RunPython.noop)
    ]
