# Generated by Django 2.0.9 on 2018-11-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181101_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=8, null=True, verbose_name='Current plan'),
        ),
    ]
